# Global configuration options. The `queue_ahead` and `tz` options can also be set on each task.
queue_ahead: 360 # Number of minutes to queue jobs into the future
queue_name: "default" # The Sidekiq queue name used by SimpleScheduler::FutureJob
tz: "America/Chicago" # The application time zone will be used by default if not set

discussion_task:
  class: 'Discussions::PublishJob'
  every: '1.hours'
  at: "*:00"

tweet_task:
  class: 'Tweets::PublishJob'
  every: '1.hours'
  at: "*:15"

assembly_task:
  class: 'AssembleJob'
  every: '30.minutes'
  at: "*:00"

imagination_task:
  class: 'Images::ImagineImagesJob'
  every: '30.minutes'
  at: "*:00"
